### ISSUE TITLE
Bounding box Experiment

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistMLWork#21]
Run an experiment to determine the impact of bounding boxes on suggestion accuracy on a sample by comparing the following scenarios:
1. no bounding box
2. bounding box predictions generated by one or more out-of-the-box bounding models
3. bounding boxes created by human annotators

**Comment by alexshepard** [comment]
Next steps for bounding box experiment:

1. do a more in-depth comparison of the image preprocessing pipeline: 85% center crop, squash and no squash, (#24)
2. replicate the salience bounding box prototype that I build using Apple technologies to use tensorflow models, (#39)
3. get an open source bounding box annotation tool working so that we can hand-annotate some labels for comparison against no bounding boxes and salience bounding boxes. (#40)

**Comment by alexshepard** [comment]
I'm going to close the bounding box experiment since I did this experiment, shared my results in a presentation to the team and IMO all of the necessary followup work is captured in these three next step issues.
